# Generated by Django 4.0.4 on 2022-08-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.ImageField(upload_to='auctions/files/listings_pictures'),
        ),
    ]
